DROP DATABASE IF EXISTS renovation_mindmap;
CREATE DATABASE renovation_mindmap
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE renovation_mindmap;

CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS nodes (
  id INT PRIMARY KEY AUTO_INCREMENT,
  node_id INT NOT NULL, -- 当前节点的ID
  name TEXT NOT NULL,
  parent_id INT,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE node_details (
  id INT PRIMARY KEY AUTO_INCREMENT,
  parent_id INT NOT NULL, -- 关联到nodes表的ID
  details TEXT CHARACTER SET utf8mb4 NOT NULL,
  image VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
